AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - node_modules/**/*
Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
